baseURL = 'https://blog.traewelling.de/'
languageCode = 'de-de'
title = 'Träwelling Blog'
theme = "tale"
sectionPagesMenu = "main"

[Author]
    name = "Das Träwelling Team"

[taxonomies]
   tag = "tags"
   category = "categories"


[menu]
   [[menu.main]]
     name = 'Über Träwelling'
     url = 'https://traewelling.de/about'
     weight = -110
   [[menu.main]]
     name = 'Serverstatus'
     url = 'https://status.traewelling.de'
     weight = -100
   [[menu.main]]
     name = 'Twitter'
     url = 'https://twitter.com/traewelling'
     weight = -90
   [[menu.main]]
     name = 'Mastodon'
     url = 'https://chaos.social/@traewelling'
     weight = 80

