baseURL = 'https://blog.traewelling.de/'
locale = 'de-de'
title = 'Träwelling Blog'
theme = "tale"
sectionPagesMenu = "main"

[params]
    [params.author]
        name = "Das Träwelling Team"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[taxonomies]
   tag = "tags"
   category = "categories"


[menu]
   [[menu.main]]
     name = 'Über Träwelling'
     url = 'https://traewelling.de/about'
     weight = -110
   [[menu.main]]
     name = 'Serverstatus'
     url = 'https://status.traewelling.de'
     weight = -100
   [[menu.main]]
     name = 'Mastodon'
     url = 'https://chaos.social/@traewelling'
     weight = 80

